import React from 'react';

export const metadata = {
    title: "Keen Keeper Website | Stats Page",
    description: "This website is generated by Next App for keeping & building friendship.",
};

const StatsPage = () => {
    return (
        <div>
            <h2>Hello Stats Page</h2>
        </div>
    );
};

export default StatsPage;