
export const metadata = {
    title: "Keen Keeper Website | Stats Page",
    description: "This website is generated by Next App for keeping & building friendship.",
};

import StatsClientPage from "./StatsClientPage";

export default function StatsPage() {
    return <StatsClientPage></StatsClientPage>
}