import React from 'react';

export const metadata = {
    title: "Keen Keeper Website | Timeline Page",
    description: "This website is generated by Next App for keeping & building friendship.",
};

const TimelinePage = () => {
    return (
        <div>
            <h2>Hello Timeline Page</h2>
        </div>
    );
};

export default TimelinePage;