export const metadata = {
    title: "Keen Keeper Website | Timeline Page",
    description: "This website is generated by Next App for keeping & building friendship.",
};

import TimelineClientPage from './TimelineClientPage';

export default function TimelinePage() {
    return <TimelineClientPage />;
}
