

export const metadata = {
  title: "Keen Keeper Website | Home Page",
  description: "This website is generated by Next App for keeping & building friendship.",
};

export default function Home() {
  return (

    <h2 className="text-2xl font-bold bg-amber-200 text-center">Hello Next.js</h2>


  );
}
