import Banner from "@/components/homePage/Banner";
import Friends from "@/components/homePage/Friends";


export const metadata = {
  title: "Keen Keeper Website | Home Page",
  description: "This website is generated by Next App for keeping & building friendship.",
};

export default function Home() {
  return (

    <div>
      <Banner></Banner>
      <Friends></Friends>

    </div>


  );
}
