import Banner from "@/components/homePage/Banner";


export const metadata = {
  title: "Keen Keeper Website | Home Page",
  description: "This website is generated by Next App for keeping & building friendship.",
};

export default function Home() {
  return (

    // <h2 className="text-2xl font-bold bg-[#F8FAFC] text-center">Hello Next.js</h2>

    <Banner></Banner>


  );
}
